"""Add CoverLetter model for AI-generated cover letters

Revision ID: 30646f248885
Revises: ece2da525316
Create Date: 2025-11-15 18:12:30.353165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30646f248885'
down_revision: Union[str, Sequence[str], None] = 'ece2da525316'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cover_letters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('job_posting_id', sa.Integer(), nullable=True),
    sa.Column('tailored_resume_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('opening_paragraph', sa.Text(), nullable=True),
    sa.Column('body_paragraphs', sa.JSON(), nullable=True),
    sa.Column('closing_paragraph', sa.Text(), nullable=True),
    sa.Column('template_id', sa.String(length=50), nullable=True),
    sa.Column('tone', sa.String(length=50), nullable=True),
    sa.Column('length', sa.String(length=20), nullable=True),
    sa.Column('focus_areas', sa.JSON(), nullable=True),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('ai_prompt_used', sa.Text(), nullable=True),
    sa.Column('ai_model', sa.String(length=100), nullable=True),
    sa.Column('user_edited', sa.Boolean(), nullable=False),
    sa.Column('edit_history', sa.JSON(), nullable=True),
    sa.Column('used_in_application_id', sa.Integer(), nullable=True),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('job_title', sa.String(length=200), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_postings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tailored_resume_id'], ['tailored_resumes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['used_in_application_id'], ['job_applications.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cover_letters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cover_letters_job_posting_id'), ['job_posting_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cover_letters_profile_id'), ['profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cover_letters_tailored_resume_id'), ['tailored_resume_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cover_letters_used_in_application_id'), ['used_in_application_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cover_letters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cover_letters_used_in_application_id'))
        batch_op.drop_index(batch_op.f('ix_cover_letters_tailored_resume_id'))
        batch_op.drop_index(batch_op.f('ix_cover_letters_profile_id'))
        batch_op.drop_index(batch_op.f('ix_cover_letters_job_posting_id'))

    op.drop_table('cover_letters')
    # ### end Alembic commands ###
