"""add selected_accomplishments_json to tailored_resumes

Revision ID: 6691c13b20f9
Revises: 7511b5df92b2
Create Date: 2025-11-18 09:36:37.135691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6691c13b20f9'
down_revision: Union[str, Sequence[str], None] = '7511b5df92b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tailored_resumes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected_accomplishments_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tailored_resumes', schema=None) as batch_op:
        batch_op.drop_column('selected_accomplishments_json')

    # ### end Alembic commands ###
