"""Add job_postings and tailored_resumes tables

Revision ID: 8482904c82bb
Revises: d8eaf3acb5a7
Create Date: 2025-11-14 11:36:29.467351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8482904c82bb'
down_revision: Union[str, Sequence[str], None] = 'd8eaf3acb5a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_postings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('job_title', sa.String(length=200), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('cleaned_text', sa.Text(), nullable=True),
    sa.Column('requirements_json', sa.Text(), nullable=True),
    sa.Column('analysis_method', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_postings_profile_id'), ['profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_postings_uploaded_at'), ['uploaded_at'], unique=False)

    op.create_table('tailored_resumes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('job_posting_id', sa.Integer(), nullable=False),
    sa.Column('selected_accomplishment_ids', sa.Text(), nullable=False),
    sa.Column('skill_coverage_json', sa.Text(), nullable=True),
    sa.Column('coverage_percentage', sa.Float(), nullable=True),
    sa.Column('gaps_json', sa.Text(), nullable=True),
    sa.Column('recommendations_json', sa.Text(), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_postings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tailored_resumes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tailored_resumes_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tailored_resumes_job_posting_id'), ['job_posting_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tailored_resumes_profile_id'), ['profile_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tailored_resumes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tailored_resumes_profile_id'))
        batch_op.drop_index(batch_op.f('ix_tailored_resumes_job_posting_id'))
        batch_op.drop_index(batch_op.f('ix_tailored_resumes_created_at'))

    op.drop_table('tailored_resumes')
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_postings_uploaded_at'))
        batch_op.drop_index(batch_op.f('ix_job_postings_profile_id'))

    op.drop_table('job_postings')
    # ### end Alembic commands ###
